#!/bin/bash
#
##
#better starter for s2
if [[ $1 == "-h" || $1 == "--help" || $# == 0 ]]; then
    echo "Give gjf-files as args"
    echo "OR -n \$nodes -f \$files"
    exit 0
elif [[ $1 == "-n" ]]; then
    [[ "$@" != *" -f "* ]] && echo "use -f \$files" && exit 1
    nodes_free=()
    shift
    while [[ $1 != "-f" ]]; do
        nodes_free+=( $1 )
        shift
    done
    shift
else
    nodes_used=($(qstat -u koen | tail -n+6 | awk '{print $3}' | sort | uniq | wc -l))
    [[ $nodes_used == 5 ]] && echo "no free nodes, use -n/-f" && exit 2
    nodes_free=($(/home/koen/.scrpts/qsmk2.sh | grep Free | awk '{print $2" "$3" "$4" "$5" "$6}'))
fi

totfiles=( "$@" )
nds=()
#for ((i=0;i<=${#totfiles[@]};i++)); do
for i in $(seq 0 $((${#totfiles[@]}-1))); do
    [[ ${#nds[@]} -lt ${#totfiles[@]} ]] && nds+=( "${nodes_free[@]}" )
    /home/koen/.scrpts/s2 $1 ${nds[$i]}
#    echo "$1 ${nds[$i]}"
    shift
done
